### ISSUE TITLE
你好，我加载了插件系统的挂件，重启以后也没有看到插件按钮

### ISSUE THREAD

**Issue by Yuminis98** [zuoez02/siyuan-plugin-system-widget#1]
![image](https://user-images.githubusercontent.com/117956441/227860925-47a14737-0f3d-4107-8c5a-91c1a0ad293e.png)
![image](https://user-images.githubusercontent.com/117956441/227860945-94229f0a-8764-4439-a8c6-55deb6115226.png)

**Comment by zuoez02** [comment]
是我代码写的问题，自动加载的路径有错误。新版本修复了这个问题，请等待集市挂件更新。

**Comment by Yuminis98** [comment]
> 是我代码写的问题，自动加载的路径有错误。新版本修复了这个问题，请等待集市挂件更新。

好嘞。

**Comment by zuoez02** [comment]
@Yuminis98 新版本已经发布了，更新一下，再添加一次挂件，然后终止之后重启一下看看

**Comment by AugustTuan** [comment]
可以了

**Comment by Yuminis98** [comment]
可以了
