### ISSUE TITLE
目前这个插件是不是还是只能用于electron 构建的桌面端呢？

### ISSUE THREAD

**Issue by lyd420** [zuoez02/siyuan-plugin-system-widget#4]
目前这个插件是不是还是只能用于electron 构建的桌面端呢？

**Comment by zuoez02** [comment]
目前是的，后续会改成基于api的实现，满足web端的能力需求。不过也会在思源2.8.1之后的版本才能实现。

**Comment by lyd420** [comment]
> 目前是的，后续会改成基于api的实现，满足web端的能力需求。不过也会在思源2.8.1之后的版本才能实现。

不管怎么说，都很感谢大佬的付出，期待后续更新
