### ISSUE TITLE
插件下载启用后不生效

### ISSUE THREAD

**Issue by zooyoo** [zuoez02/siyuan-plugin-system-widget#7]
挂件已下载按要求注册，右上角也看得到按钮，但下载了一些插件，也启用了，都不生效啊

重载或者重启思源都不生效，

比如彩色文件树、会员功能隐藏都启用了，实际上并没有生效，文件树右键并没有颜色设置，会员按钮也还存在

这是咋回事？

**Comment by sq98** [comment]
我这MacOS siyuan2.8.3，会员功能隐藏 打开启用，正常有效。
但是彩色文件树打开后，点击文件树右键 并没有颜色设置，即无效。
点击文档树哪里，可以说具体一些吗？

**Comment by zuoez02** [comment]
@zooyoo 关闭插件系统配置里的安全模式

**Comment by zuoez02** [comment]
@sq98 这个需要问插件的开发者了

**Comment by zooyoo** [comment]
> @zooyoo 关闭插件系统配置里的安全模式

可以了，晕，我以为勾上是表示关闭。。而且默认是勾上的，原来不勾才是关闭安全模式

**Comment by zooyoo** [comment]
已解决

**Comment by sq98** [comment]
@zuoez02 @zooyoo 摸索了一下，彩色文件树 可以使用了。
彩色文件树打开后，
方法一：右键点击文档树里的文档，等待约一秒钟后，即可在右键菜单里最后一项看到 修改颜色 选项。
方法二：打开的某文档，然后右键点击它标签的文档名，即可在右键菜单里最后一项看到 修改颜色 选项。
注意：文档笔记可以修改颜色，最外层的笔记本是无法修改颜色的。同步时  修改颜色 选项 可能会延迟显示，同步结束后，则正常显示 修改颜色 选项 。
